### ISSUE TITLE
Trying again after eth_call RPC call failed

### ISSUE THREAD

**Issue by AlexVorobiov** [graphprotocol/graph-node#2265]
similarly to #1315
I am getting this error repetitively and my subgraph get stuck :

> Trying again after eth_call RPC call failed with result Err(Web3Error(Rpc(Error { code: ServerError(-32000), message: "stack limit reached 1024 (1023)", data: None }))), runtime_host: 1/1, block_hash: 0xd1eef981491a432fa3e8b8d09b15d2f7c7c86c4b7f65f75655b515715064608e, block_number: 11430213

This might be related to the following contract: 0xd2d2a84f0eb587f70e181a0c4b252c2c053f80cb

**Comment by leoyvens** [comment]
Do you have a link to a subgraph that triggers this, on the explorer and preferrably a commit in a repo?

**Comment by AlexVorobiov** [comment]
> Do you have a link to a subgraph that triggers this, on the explorer and preferrably a commit in a repo?

sure https://thegraph.com/explorer/subgraph/alexvorobiov/eip1155subgraphdev?selected=logs

**Comment by leoyvens** [comment]
Resolved by #2346

**Comment by forkollaider** [comment]
still reproducible for me when launch graph node with docker-compose locally. just docker-compose up

**Comment by maoueh** [comment]
@forkollaider Retryable errors vs deterministic errors is a bit hard to get right since there is no standard. If you could provide more details like the node that is providing the data (name & version) as well as the exact error message you get, that would help.

Some changes were made recently around RPC error handling, and some configurability has been added, so a simple configuration change could resolve the issue.

**Comment by makemyidea** [comment]
<img width="1135" alt="Screen Shot 2021-11-03 at 3 31 14 PM" src="https://user-images.githubusercontent.com/63793139/140040797-7a14d1ba-aac4-4a2b-8461-3ba1d88ccd73.png">

@maoueh @leoyvens - i am also getting same error. Do I have to redeploy my subgraph?

**Comment by azf20** [comment]
hi @makemyidea , are you still having this issue? can you link to the affected subgraph?

**Comment by makemyidea** [comment]
@azf20 getting this error now.

Trying again after eth_call RPC call failed (attempt #2) with result Err(Web3Error(Transport("Unexpected response status code: 502 Bad Gateway"))), block_hash:

**Comment by Danijel-Enoch** [comment]
still getting this error

**Comment by azf20** [comment]
hi @Danijel-Enoch can you give a bit more context on where you are encountering this error?
