### ISSUE TITLE
Hosted service new deployment not syncing

### ISSUE THREAD

**Issue by qbig** [graphprotocol/graph-node#2306]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
after successful deployment, syncing got stuck
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
https://thegraph.com/explorer/subgraph/synfutures/erc7?version=pending
**What is the expected behavior?**

```
3/23/2021, 8:16:40 PM

DEBUG

Trying again after object.stat failed (attempt #4) with result Err(Uncategorized("<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.19.6</center>\r\n</body>\r\n</html>\r\n"))

3/23/2021, 8:16:10 PM

DEBUG

Trying again after object.stat failed (attempt #3) with result Err(Uncategorized("<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.19.6</center>\r\n</body>\r\n</html>\r\n"))

3/23/2021, 8:15:09 PM

DEBUG

Trying again after object.stat failed (attempt #1) with result Err(Uncategorized("<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.19.6</center>\r\n</body>\r\n</html>\r\n"))
```

**Comment by novaknole** [comment]
Same.. In my case, it gets stuck with 90.8% and then, after an hour or 2, succeeds. 

Hope it will be resolved soon.

**Comment by qbig** [comment]
Normally, if there is an bug in the mappings, syncing would turn into "Failed" state with some error logs telling us what's wrong. But in my case there is no errors, and it just got stuck forever :(

**Comment by qbig** [comment]
![image](https://user-images.githubusercontent.com/5563225/112251012-62c49c00-8c95-11eb-92a0-4d3d2cd2cc8e.png)
![image](https://user-images.githubusercontent.com/5563225/112251034-7112b800-8c95-11eb-8d6f-e21ce55f93b4.png)

**Comment by hzz780** [comment]
![image](https://user-images.githubusercontent.com/7567714/112266143-9829b380-8cae-11eb-93e7-b042b24322e3.png)

Same....

 I can not event deploy the hello world of the docs with small change.

**Comment by milonite** [comment]
Same here, it reaches 99.9% but does not become the current version. No errors, warnings, Infos found.

**Comment by leoyvens** [comment]
Please provide links to the subgraphs on the explorer so we can better investigate this issue.

**Comment by m30m** [comment]
Mine is the same:
Here is the link:
https://thegraph.com/explorer/subgraph/creaton-io/creaton2

**Comment by leoyvens** [comment]
I have confirmed that we have an issue were the graph nodes sometimes stop receiving new deployments, requiring a restart of the nodes. I have reset all nodes so the current incident should be resolved. Until we root cause this, please report on Discord if this happens again.

**Comment by milonite** [comment]
Seems that the restart unlocked the current pending version (with correct logging) but the same issue reappears if I try to re-deploy.

**Comment by qbig** [comment]
This is resolved now. Thanks for the prompt response @leoyvens

**Comment by qbig** [comment]
Er... this is still happening to people I think @leoyvens

**Comment by lutter** [comment]
Could you provide an example of a subgraph where this is still happening?

**Comment by qbig** [comment]
@lutter Thanks for the reply:
https://thegraph.com/explorer/subgraph/synfutures/erc7?version=pending

**Comment by leoyvens** [comment]
@qbig that subgraph seems to be making progress, what is the issue?

**Comment by lutter** [comment]
It is making progress, just very slowly - it's making a ton of ethereum calls. Over the last 22 hours, it has spent all but 40 minutes in ethereum calls. There's little we can do to speed that up. Each call takes 100-150ms. To speed this subgraph up, you'd need to change it so it does fewer ethereum calls.

**Comment by qbig** [comment]
@lutter wow！Thanks for the tip! Removing ethereum calls works. However, this is kinda related to https://github.com/graphprotocol/graph-node/issues/2314 because without filter, I would be making calls for every block :(

**Comment by qbig** [comment]
@lutter  another issue is this, as new deployments is ignored.
quote @leoyvens
```
I have confirmed that we have an issue were the graph nodes sometimes stop receiving new deployments, requiring a restart of the nodes. I have reset all nodes so the current incident should be resolved. Until we root cause this, please report on Discord if this happens again.
```

**Comment by leoyvens** [comment]
@qbig That incident has been resolved, are you still having issues with new deployments?

**Comment by leoyvens** [comment]
Please open a new issue if necessary.

**Comment by itsib** [comment]
I have same issue with my subgraph. In the matic network.
https://thegraph.com/legacy-explorer/subgraph/itsib/spaceport-subgraph-polygon

**Comment by yohanelly95** [comment]
Hello, my subgraph seems to be stuck while deploying and there seem to be no error logs etc. - https://thegraph.com/hosted-service/subgraph/yohanelly95/razor?version=pending 

Are there any suggestions on anything I can do?

**Comment by lutter** [comment]
> Hello, my subgraph seems to be stuck while deploying and there seem to be no error logs etc. - https://thegraph.com/hosted-service/subgraph/yohanelly95/razor?version=pending
> 
> Are there any suggestions on anything I can do? cc @leoyvens

@yohanelly95 we had an issue with one of the index nodes earlier. It looks like your subgraph is processing again.

**Comment by yohanelly95** [comment]
> > Hello, my subgraph seems to be stuck while deploying and there seem to be no error logs etc. - https://thegraph.com/hosted-service/subgraph/yohanelly95/razor?version=pending
> > Are there any suggestions on anything I can do? cc @leoyvens
> 
> @yohanelly95 we had an issue with one of the index nodes earlier. It looks like your subgraph is processing again.

yes it is, I just had to redeploy a few times. Thanks again 🥇

**Comment by sid5494** [comment]
@leoyvens I have tried redeploying many times, also waited for a week but syncing stopped at 68.3% is there any possible way to overcome this issue here is my link https://thegraph.com/hosted-service/subgraph/sid5494/fantom?version=pending. Are there any suggestions on anything I can do?

**Comment by Muzikanto** [comment]
https://thegraph.com/hosted-service/subgraph/muzikanto/mf-nft
![image](https://user-images.githubusercontent.com/31695401/152356547-105fbf95-a076-4258-ad1b-34ff1fd5711d.png)

**Comment by DecentraWorldOfficial** [comment]
> I have confirmed that we have an issue were the graph nodes sometimes stop receiving new deployments, requiring a restart of the nodes. I have reset all nodes so the current incident should be resolved. Until we root cause this, please report on Discord if this happens again.

Hey there, I'm having a similar issue with fantom network.
https://thegraph.com/hosted-service/subgraph/decentraworlddewo/fantom-demix-subgraph

Is there anything I can do about it? I've tried re-deploying but the same issue occurs.

**Comment by mtwichan** [comment]
Bump. I'm getting this issue on AVAX Fuji.
